import { TemplateDefinition } from "./types";

export const templates: TemplateDefinition[] = [
  {
    id: "professional",
    name: "Professional",
    description: "Navy & gold, serif headings, elegant rule lines",
    tokens: {
      fontHeading: "Georgia, 'Palatino Linotype', 'Book Antiqua', serif",
      fontBody: "'Segoe UI', 'Helvetica Neue', system-ui, sans-serif",
      colorPrimary: "#1e293b",
      colorSecondary: "#64748b",
      colorAccent: "#b8860b",
      colorBackground: "#ffffff",
      colorText: "#334155",
      sectionSpacing: "1.8rem",
      lineHeight: "1.75",
    },
    decorations: {
      headerStyle: "bar",
      sectionNumberStyle: "plain",
      borderStyle: "none",
      hasWatermark: false,
      hasPageBorder: false,
    },
  },
  {
    id: "corporate",
    name: "Corporate",
    description: "Bold gradient header, numbered circles, strong hierarchy",
    tokens: {
      fontHeading: "'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
      fontBody: "'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
      colorPrimary: "#0f172a",
      colorSecondary: "#475569",
      colorAccent: "#2563eb",
      colorBackground: "#ffffff",
      colorText: "#1e293b",
      sectionSpacing: "1.6rem",
      lineHeight: "1.7",
    },
    decorations: {
      headerStyle: "block",
      sectionNumberStyle: "circle",
      borderStyle: "none",
      hasWatermark: false,
      hasPageBorder: false,
    },
  },
  {
    id: "modern",
    name: "Modern",
    description: "Gradient stripe accent, pill badges, airy whitespace",
    tokens: {
      fontHeading: "'Helvetica Neue', system-ui, -apple-system, sans-serif",
      fontBody: "'Helvetica Neue', system-ui, -apple-system, sans-serif",
      colorPrimary: "#18181b",
      colorSecondary: "#71717a",
      colorAccent: "#6366f1",
      colorBackground: "#ffffff",
      colorText: "#3f3f46",
      sectionSpacing: "2.2rem",
      lineHeight: "1.8",
    },
    decorations: {
      headerStyle: "stripe",
      sectionNumberStyle: "pill",
      borderStyle: "left-accent",
      hasWatermark: false,
      hasPageBorder: false,
    },
  },
  {
    id: "classic",
    name: "Classic Legal",
    description: "Traditional double-bordered, Times New Roman, formal",
    tokens: {
      fontHeading: "'Times New Roman', 'Palatino Linotype', Georgia, serif",
      fontBody: "'Times New Roman', 'Palatino Linotype', Georgia, serif",
      colorPrimary: "#1a1a1a",
      colorSecondary: "#4a4a4a",
      colorAccent: "#2d2d2d",
      colorBackground: "#fffef8",
      colorText: "#1a1a1a",
      sectionSpacing: "1.4rem",
      lineHeight: "1.65",
    },
    decorations: {
      headerStyle: "minimal",
      sectionNumberStyle: "indent",
      borderStyle: "double",
      hasWatermark: false,
      hasPageBorder: true,
    },
  },
  {
    id: "startup",
    name: "Startup",
    description: "Vibrant gradient header, modern rounded elements",
    tokens: {
      fontHeading: "'Segoe UI', system-ui, -apple-system, sans-serif",
      fontBody: "'Segoe UI', system-ui, -apple-system, sans-serif",
      colorPrimary: "#18181b",
      colorSecondary: "#71717a",
      colorAccent: "#8b5cf6",
      colorBackground: "#ffffff",
      colorText: "#27272a",
      sectionSpacing: "1.8rem",
      lineHeight: "1.75",
    },
    decorations: {
      headerStyle: "gradient",
      sectionNumberStyle: "pill",
      borderStyle: "none",
      hasWatermark: false,
      hasPageBorder: false,
    },
  },
  {
    id: "executive",
    name: "Executive",
    description: "Letterhead style, small-caps, confidential watermark",
    tokens: {
      fontHeading: "Georgia, 'Palatino Linotype', 'Book Antiqua', serif",
      fontBody: "'Segoe UI', 'Helvetica Neue', system-ui, sans-serif",
      colorPrimary: "#1a1a2e",
      colorSecondary: "#555580",
      colorAccent: "#1a1a2e",
      colorBackground: "#fefefe",
      colorText: "#2a2a4a",
      sectionSpacing: "1.6rem",
      lineHeight: "1.7",
    },
    decorations: {
      headerStyle: "letterhead",
      sectionNumberStyle: "underline",
      borderStyle: "single",
      hasWatermark: true,
      hasPageBorder: false,
    },
  },
];

export function getTemplate(id: string): TemplateDefinition {
  return templates.find((t) => t.id === id) || templates[0];
}
